function f() { throw "err"; }

x = "";
try {
  y = f();
} catch (x)
assert(x == "err");
