f = () => throw "err"

x = try y = f()
assert (= x "err")
