let f = () => throw "err"

let x = try let y = f()
assert (= x "err")
